const express = require('express')
const router = express.Router()
const Interview = require('../models/Interview')
const Assessment = require('../models/Assessment')
const Candidate = require('../models/Candidate')

// POST /api/interviews/start
router.post('/start', async (req, res) => {
  try {
    const { candidateId } = req.body
    if (!candidateId) return res.status(400).json({ message: 'candidateId required' })
    const interview = new Interview({ candidateId, startTime: new Date() })
    await interview.save()
    res.status(201).json(interview)
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})

// POST /api/interviews/:id/transcript — append transcript entries
router.post('/:id/transcript', async (req, res) => {
  try {
    const { entries } = req.body  // [{ role, text }]
    const interview = await Interview.findById(req.params.id)
    if (!interview) return res.status(404).json({ message: 'Interview not found' })
    if (entries && Array.isArray(entries)) {
      interview.transcript.push(...entries)
    }
    await interview.save()
    res.json(interview)
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})

// POST /api/interviews/:id/complete
router.post('/:id/complete', async (req, res) => {
  try {
    const { duration } = req.body
    const interview = await Interview.findById(req.params.id)
    if (!interview) return res.status(404).json({ message: 'Interview not found' })
    interview.status = 'completed'
    interview.endTime = new Date()
    interview.duration = duration
    interview.phase = 'complete'
    await interview.save()
    // Update candidate status
    await Candidate.findByIdAndUpdate(interview.candidateId, { status: 'completed' })
    res.json(interview)
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})

// POST /api/interviews/:id/assess — placeholder for Gemini AI assessment
router.post('/:id/assess', async (req, res) => {
  try {
    const interview = await Interview.findById(req.params.id)
    if (!interview) return res.status(404).json({ message: 'Interview not found' })

    // Placeholder assessment — will be replaced by Gemini API call
    const assessment = new Assessment({
      interviewId: interview._id,
      candidateId: interview.candidateId,
      overallScore: 4.0,
      recommendation: 'Maybe',
      dimensions: [
        { name: 'Teaching Ability', score: 4.0, evidence: 'AI assessment pending — Gemini integration required.' },
        { name: 'Communication',    score: 4.0, evidence: 'AI assessment pending.' },
        { name: 'Temperament',      score: 4.0, evidence: 'AI assessment pending.' },
        { name: 'Confidence',       score: 4.0, evidence: 'AI assessment pending.' },
        { name: 'Environment',      score: 4.0, evidence: 'AI assessment pending.' },
      ],
      strengths:    ['Assessment will be generated by Gemini AI'],
      improvements: ['Assessment will be generated by Gemini AI'],
    })
    await assessment.save()
    await Candidate.findByIdAndUpdate(interview.candidateId, { status: 'assessed' })
    res.status(201).json(assessment)
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})

// GET /api/interviews — list all (admin)
router.get('/', async (req, res) => {
  try {
    const interviews = await Interview.find().populate('candidateId').sort({ startTime: -1 })
    res.json(interviews)
  } catch (err) {
    res.status(500).json({ message: err.message })
  }
})

module.exports = router
